### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#1016]
I don't think we'll have time to get this into Release 4.2, but maybe in some point releases.
- [x] README up-to-date + index for the docs folder [PR #1066]
- [x] Documentation of the utilities in build directory. Or maybe take them out of there? [PR #1049]
- [x] ~~Document the classes/methods/functions in the tool (this should be divided into sub-categories for tracking)~~ [Postponed #1125]
- [x] Add a document (or append to an existing one) addressing the first comment below (from AndrewB) [PR #1078]
- [x] The readmes inside the vulClasses need to be revised. [PR #1096]
- [x] Add a readme in `./besspin/cwesEvaluation/multitasking/`: [PR #1140]
    - Explain the multitasking in more details
    - Explicitly mention the claims made by those scores
    - Write how the scores (the last column) is calculated
    - Add a link to this document in `./docs/cwesEvaluation/configuration.md`.
