### ISSUE TITLE
The long awaited renaming

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#1045]
Pre-requisites: 

- [x] Merging `organize-and-readmes`
- [x] Merging `update-readmes-and-docs`
- [x] 1-2 weeks notice to all concerned parties. (sent on 3/29)

The initial renaming plan is:
- [x] Rename `SSITH-FETT-Target` to `BESSPIN-Tool-Suite`
- [x] Rename `SSITH-FETT-Environment` to `BESSPIN-Environment`
- [x] Rename `SSITH-FETT-Binaries` to `BESSPIN-LFS`
- [x] Rename `SSITH-FETT-Voting` to `BESSPIN-Voter-Registration`

The post-open-source renaming:
- [x] Rename `${repo}/fett` to `${repo}/besspin` [PR #1083]
- [x] Rename `${repo}/fett.py` to `${repo}/besspin.py` [PR #1083]
- [x] Rename `${repo}/besspin/apps` to `${repo}/besspin/fett` [PR #1105]
- [x] FreeRTOS:
    - [x] `FETT_APPS`, `main_fett` macros/functions/headers inside FreeRTOS submodules. [PR #1083]
    - [x] `testgen` macros [PR #1086]
    - [x] The headers and functions names [PR #1083]
    - [x] The `.mk` files [PR #1083]
- [x] Update documents and readmes [PR #1083]
