### ISSUE TITLE
Cyberphys state machines tracking issue

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/BESSPIN-Tool-Suite#1070]
We need the following state machine diagrams:
- [x]  FETT tool
- [x] Ignition
- [ ] Hacker kiosk / Debug console
  - TBD should coordinate with Steven
- [x] Infotainment thin client
- [x] Driver experience
- [x] Hacker experience
- [ ] ~~Admin (debug/maintenance) experience~~
  - A simple way to exit to the terminal is probably enough for now
  - And all events should be logged (CAN.log, C&C.log)

PR #1052 closes this

**Comment by podhrmic** [comment]
Closing as the state machines are mostly complete, and the hacker kiosk is currently well defined even without an explicit state machine.
