### ISSUE TITLE
Open Source BESSPIN

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#1076]
**{Continuously Updated Task List}**
- [x] Create an `open-source` label, and label all tickets that are pre-requisite to open-sourcing.
- [x] Make sure all the binaries in the LFS repo are ok to release [#1126]
- [x] Docker: Make sure all the containers are available publicly.
    - [x] Move and re-structure [DARPA-SSITH-Demonstrators/SSITH-FETT-Environment#61]
    - [x]  minor modifications in BESSPIN-Environment
    - [x] Re-build
    - [x] Push all (post public)
- [x] Go through the [sharing policy document](https://docs.google.com/document/d/1heGRH0uNUMP-Ju1GjygB6UCRqoGnZmpkQSbhEnuqPEQ/edit#heading=h.n5t7nqghg1fd) approved by Keith, and make sure all the artifacts are ported to Github.
- [x] Ensure all tickets labeled `open-source` are closed.
- [x] Move ownership to `Galois` (dependent on some of the tasks in #1045)
- [x] Release testing
- [x] Actually open-source the repos [tracker spreadsheet](https://docs.google.com/spreadsheets/d/1VPDOSBSLhkios4kkC-LgUldvGXBj-mk2KtPVaj7XgvY/edit#gid=0)

**Comment by rtadros125** [comment]
Forgot to close this one. Now everything is public and for everyone to see :)
