### ISSUE TITLE
Implement the decision that comes out of the discussion of segfaults

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#1122]
Based on the outcomes of the the discussion in #1121 when it ends, we need to make sure that all of the following are consistent:
- [x] The BESSPIN philosophy document (PR #1131)
- [x] Scoring of: (PR #1124)
    - [x] buffer errors (PR #1124)
    - [x] PPAC (Double checked, no changes needed)
    - [x] resource management (PR #1124)
    - [x] information leakage (Double checked, no changes needed)
    - [x] numeric errors (Double checked, no changes needed)
    - [x] injection (PR #1124)
- [ ] Custom scoring and its adjustments 
- [ ] Additional tasks stemming from the discussion in #1121:
    - [ ] `<placeholder>`
