### ISSUE TITLE
SimPC outstanding issues

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/BESSPIN-Tool-Suite#1150]
- [x] Ignition doesn't seem to manage the LEDs #1166
- [x] Make sure Ignition starts in full-screen #1165
- [x] Autostart ignition after boot (no user input needed) #1167 
- [x] Add documentation about calibrating the steering wheel #1171
- [x] Infotainment client (the screen) doesn't seem to work (buttons have no effect)
- [x] ~~After manually ('R' key) resetting a scenario, a key still needs to be pressed after a restart~~
- [x] The timeout for switching into self-driving mode is very short (it occurs ~5 s  after start)
- [x] Parsing the GEAR CAN message doesn't work properly in ignition - perhaps the CANFORMAT is wrong?
- [x] Camera needs adjustment - no dash/front hood, better wide-angle experience (currently it makes me dizzy)
- [x] Wifi doesn't seem to connect automatically after start (hard for remote access)

**Comment by podhrmic** [comment]
Closing, as the last items were the infotainment buttons - and they do have an effect, just are very slow. Tracking that one separately.
