### ISSUE TITLE
Respond to DISTAR for open-sourcing

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#1154]
Items that need to be addressed:

- [x] Missing FETT Portal (Opened #1153) (GaloisInc/BESSPIN#5)
- [x] Need high level description of what the repos are and where things are for example the cyber physical demo is buried in the BESSPIN tool suite directory where no one will know where it is (GaloisInc/BESSPIN#2, in progress - @dmzimmerman)
- [x] Need a get started guide for new users
- [x] Need to document where items in BESSPIN-LFS came from and what version/date the processors are (GaloisInc/BESSPIN-LFS#150)
- [x] Xilinx proprietary files are found in the BSC-sourcelib-support directory (GaloisInc/BESSPIN#5)
