### ISSUE TITLE
Add AWS support to fett.py -- PV Firesim

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#133]
What needs to be done for this:
- [x] A simple spin-up/spin-down script for performers #208
- [x] Finalize the proc-OS-PV matrix #299 
- [x] Create an AMI for PV FireSim #207 
- [x] AMI credentials? #318 
- [x] Add an AWS class and boot Debian on it #288 
- [x] Bring the minimal flow up to standards #313 
- [x] The debian build with the required drivers #291 
- [x] The FireSim Binaries #300
- [x] The FireSim shared libraries #301
- [x] Add FireSim trace as a feature, and make it configurable #302
- [x] Track down the AFIs and updating them and such #303
- [x] Check on IceNet checksum DARPA-SSITH-Demonstrators/BESSPIN-CloudGFE#93 (it does not harm; the tool works with the warnings).
- [x] Running Debian Chisel_p2 on PV Firesim #209 
- [x] Running FreeRTOS Chisel_p1 on PV Firesim #211
