### ISSUE TITLE
Bring the minimal flow up to standards

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#313]
After @EthanJamesLew merges the initial minimal flow. The following tasks need to be done. If you are going to start working on a task, please replace AVAILABLE with your name.

- [x] The AFI part. [Ethan][PR #323]
- [x] Remove `screen` commands. [Ramy][PR #320]
- [x] Use the normal runCommand. [Ramy][PR #337]
- [x] Clean up the `cwd` and `chdir` shenanigans. [Ramy][PR #320]
- [x] Deal with the netboot in a cleaner way. [Ethan][PR #340]
- [x] Implement the interact method. [Ethan][PR #326]
- [x] getClassType with variants.  [Ramy][PR #316]
- [x] Kernel modules. [Ramy][PR #321]
- [x] prepareOsImage() [Ethan][PR #340]
- [x] Booting timeout. [Ramy][PR #320]
- [x] Boot the actual image, not the minimal image. [Ramy][PR #337]
- [x] Run the network configuration part successfully + network setupEnv? [Ramy][PR #325]
- [x] Shutdown runs once well, and once not. [Ramy][PR #337]
- [x] activateEthernet method. [Ramy][PR #337]
- [x] Run app tests successfully. [Ramy][PR #342]
- [x] ~~The slot-id in the fsim command should match the slot-id from flashing the fpga. [Ramy]~~
- [x] Ensure it is all well done according to the configs. Which means that the debian parts are only executed for debian, and everything else is to be implemented. Don't program the same agfi for all, don't bring up the osImage for all, don't execute the same methods, etc. [Ramy][PR #343]
