### ISSUE TITLE
Port all testgen targets into `fett.py`

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#765]
Check qemu and fpga targets for:
- [x] Qemu:chisel_p1 [Brett] (#784)
- [x] Qemu:bluespec_p1 [Brett] (#798)
- [x] fpga:chisel_p1 [Ramy] (#781)
- [x] fpga:bluespec_p1 [Ramy]
- [x] Qemu:{chisel,bluespec}_p{2,3} (Brett)
    - [x] Debian
    - [x] FreeBSD
- [x] fpga:chisel_p2 [Ramy] (#775)
   - [x] Debian
   - [x] FreeBSD
- [x] fpga:chisel_p3[Ramy] (#825 )
   - [x] Debian
   - [x] FreeBSD
- [x] fpga:bluespec_p2 [Ramy] (#775)
   - [x] Debian
   - [x] FreeBSD
- [x] fpga: bluespec_p3 [Ramy]
   - [x] Debian
   - [x] FreeBSD
