### ISSUE TITLE
Refine Resource Management class based on the updated CWEs list

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#847]
- [x] Initial Clean-up [#899]
- [x] Test 400 [#905]
- [x] Test 404 [#905]
- [x] Test 457 [#907]
- [x] Test 463 [#916 -- Pending Austin's confirmation]
- [x] Test 467 [#907]
- [x] Test 587 [#909]
- [x] Test 590 [#911]
- [x] Test 665 [#911]
- [x] Test 668 [#913]
- [x] Test 669 [#913]
- [x] Test 672 [#911]
- [x] Test 770 [#905]
- [x] Test 789 [#905]
- [x] Test 908 [#914]
- [x] Test 909 [#914]
- [x] Test 920 [#916 -- Pending Austin's confirmation]
- [x] Check that all the mallocs (except exhaustion, etc) are not returning NULL
