### ISSUE TITLE
Refine Information Leakage class based on the updated CWEs list

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#849]
- [x] Add 200 to the cwe mapping [#922]
- [x] Test 205 [#922]
- [x] Test 206 [#922]
- [x] Test 208 [#922]
- [x] Remove 209 [#922]
- [x] Remove 214 [#922]
- [x] Test 244 [#925]
- [x] Remove 321 [#922]
- [x] Test 385 [#922]
- [x] Remove 526 [#922]
- [x] Remove 612 [#922]
- [x] Remove 707 [#922]
- [x] Can we avoid running the not-implemented combinations instead of wasting time? [#927]
- [x] Can we save the clafer result instead of wasting time re-generating the same mapping? [#927]
- [x] Add the testScore.py [#927]
