### ISSUE TITLE
Add Hardware/SOC Class and Tests

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#852]
Based on the updated CWEs list. A new class needs to be added, then for each CWE, either to have a test or to be considered a recommendation that should be evaluated subjectively:
- [x] Add a class to the tool + merge to `develop` for others to be able to collaborate [#865]
- [x] CWE-1037: Processor Optimization Removal or Modification of Security-critical Code
- [x] CWE-1050: Excessive Platform Resource Consumption within a Loop
- [x] CWE-1189: Improper Isolation of Shared Resources on System-on-Chip (SoC)
- [x] CWE-1193: Power-On of Untrusted Execution Core Before Enabling Fabric Access Control
- [x] CWE-1209: Failure to Disable Reserved Bits
- [x] CWE-1220: Insufficient Granularity of Access Control [#878]
- [x] CWE-1221: Incorrect Register Defaults or Module Parameters
- [x] CWE-1222: Insufficient Granularity of Address Regions Protected by Register Locks
- [x] CWE-1223: Race Condition for Write-Once Attributes
- [x] CWE-1224: Improper Restriction of Write-Once Bit Fields
- [x] CWE-1229: Creation of Emergent Resource
- [x] CWE-1231: Improper Implementation of Lock Protection Registers
- [x] CWE-1232: Improper Lock Behavior After Power State Transition
- [x] CWE-1233: Improper Hardware Lock Protection for Security Sensitive Controls
- [x] CWE-1234: Hardware Internal or Debug Modes Allow Override of Locks
- [x] CWE-1239: Improper Zeroization of Hardware Register [wip Ramy]
- [x] CWE-1240: Use of a Risky Cryptographic Primitive
- [x] CWE-1241: Use of Predictable Algorithm in Random Number Generator
- [x] CWE-1242: Inclusion of Undocumented Features or Chicken Bits
- [x] CWE-1243: Exposure of Security-Sensitive Fuse Values During Debug
- [x] CWE-1245: Improper Finite State Machines (FSMs) in Hardware Logic
- [x] CWE-1246: Improper Write Handling in Limited-write Non-Volatile Memories
- [x] CWE-1251: Mirrored Regions with Different Values
- [x] CWE-1252: CPU Hardware Not Configured to Support Exclusivity of Write and Execute Operations [#871 ]
- [x] CWE-1253: Incorrect Selection of Fuse Values
- [x] CWE-1254: Incorrect Comparison Logic Granularity
- [x] CWE-1256: Hardware Features Enable Physical Attacks from Software
- [x] CWE-1257: Improper Access Control Applied to Mirrored or Aliased Memory Regions
- [x] CWE-1259: Improper Protection of Security Identifiers
- [x] CWE-1260: Improper Handling of Overlap Between Protected Memory Ranges
- [x] CWE-1261: Improper Handling of Single Event Upsets
- [x] CWE-1262: Register Interface Allows Software Access to Sensitive Data or Security Settings
- [x] CWE-1264: Hardware Logic with Insecure De-Synchronization between Control and Data Channels
- [x] CWE-1268: Agents Included in Control Policy are not Contained in Less-Privileged Policy
- [x] CWE-1270: Generation of Incorrect Security Identifiers
- [x] CWE-1271: Missing Known Value on Reset for Registers Holding Security Settings 
- [x] CWE-1272: Debug/Power State Transitions Leak Information
- [x] CWE-1273: Device Unlock Credential Sharing
- [x] CWE-1274: Insufficient Protections on the Volatile Memory Containing Boot Code
- [x] CWE-1276: Hardware Block Incorrectly Connected to Larger System
- [x] CWE-1277: Firmware Not Updateable
- [x] CWE-1279: Cryptographic Primitives used without Successful Self-Test
- [x] CWE-1280: Access Control Check Implemented After Asset is Accessed
- [x] CWE-1281: Sequence of Processor Instructions Leads to Unexpected Behavior (Halt and Catch Fire)
- [x] CWE-1282: Assumed-Immutable Data Stored in Writable Memory
- [x] CWE-1283: Mutable Attestation or Measurement Reporting Data
