### ISSUE TITLE
"Last" Modifications to the CWEs list

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#935]
- [x] Simple test for CWE-463. [#941]
- [x] Add CWE-920 to HardwareSoc class. [#948]
- [x] Add CWE-208 and CWE-385 to HardwareSoc class. [#948]
- [x] Update the final CWEs list in the spreadsheet accordingly. [#948]
- [x] Add this spreadsheet to the repo in some shape or form. We need a final CWEs list somewhere! [#948]
